export const mockData = [
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/bg_blue_generic_04ef5399a0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_rare_74268217ef.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_card_34a46d66e3.png",
		text: "SIN POCIONES",
	},

	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/bg_blue_generic_04ef5399a0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_rare_74268217ef.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/manoscabeza_9a405db572.png",
		text: "A LO LOCO",
	},

	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/bg_blue_generic_04ef5399a0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/pistola_cbb26eb1dc.png",
		text: "ONLY GUNS",
	},

	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/objetossuelo_4cf65d7326.png",
		text: "TIRA OBJETOS AL SUELO ",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/saludo_d0db60bdf3.png",
		text: "DI HOLA",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/cancelaultima_e4b61f0f7f.png",
		text: "NO PUEDES AVANZAR",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/emotes_329856a1af.png",
		text: "USA TUS EMOJIS",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/jugarjuntos_a19a3c129e.png",
		text: "ELIGE COMPAÑERO DE ARMAS",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/pico_00614f7b5d.png",
		text: "PUEDES UTILIZAR EL PICO",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/singafas_5b6c9d1dd9.png",
		text: "SIN GAFAS",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/dedicarkill_54513ef5df.png",
		text: "DEDICA UN KILL",
	},
	{
		"bg-border": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/01_borde_eea64181d3.png",
		"bg-card": "https://bridder-strapi.s3.eu-central-1.amazonaws.com/1_bg_suja_a3031ebcc0.png",
		rarity: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/frame_legendary_c2e11d5b53.png",
		logo: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/Logo_Suja_1f96e7632f.png",
		img: "https://bridder-strapi.s3.eu-central-1.amazonaws.com/silencio_1f496c0edf.png",
		text: "SILENCIO",
	},
];
